import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
    throw new Error(
        'Missing Supabase environment variables. Please create a .env.local file with:\n' +
        'NEXT_PUBLIC_SUPABASE_URL=your_supabase_url\n' +
        'NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key'
    )
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Database types (simplified - will be auto-generated by Supabase CLI in production)
export type Database = {
    public: {
        Tables: {
            user_profiles: {
                Row: {
                    id: string
                    full_name: string
                    phone: string | null
                    avatar_url: string | null
                    preferred_language: string
                    created_at: string
                    updated_at: string
                }
                Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'created_at' | 'updated_at'>
                Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
            }
            food_items: {
                Row: {
                    id: string
                    category_id: string
                    name: string
                    description: string | null
                    base_price: number
                    current_price: number
                    image_url: string | null
                    is_available: boolean
                    is_vegetarian: boolean
                    is_vegan: boolean
                    allergens: string[] | null
                    preparation_time: number | null
                    calories: number | null
                    stock_quantity: number
                    low_stock_threshold: number
                    created_at: string
                    updated_at: string
                }
            }
            categories: {
                Row: {
                    id: string
                    name: string
                    description: string | null
                    image_url: string | null
                    display_order: number
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
            }
            cart_items: {
                Row: {
                    id: string
                    user_id: string
                    food_item_id: string
                    quantity: number
                    price_at_add: number
                    created_at: string
                    updated_at: string
                }
            }
            orders: {
                Row: {
                    id: string
                    user_id: string
                    order_number: string
                    status: 'pending' | 'accepted' | 'preparing' | 'out_for_delivery' | 'delivered' | 'cancelled'
                    delivery_address_id: string | null
                    delivery_address_snapshot: any
                    subtotal: number
                    discount_amount: number
                    delivery_fee: number
                    tax_amount: number
                    total_amount: number
                    promo_code_id: string | null
                    promo_code_used: string | null
                    payment_method: 'cash' | 'card' | 'upi' | 'wallet'
                    payment_status: 'pending' | 'paid' | 'failed' | 'refunded'
                    special_instructions: string | null
                    estimated_delivery_time: string | null
                    actual_delivery_time: string | null
                    created_at: string
                    updated_at: string
                }
            }
        }
    }
}
